name: workflow overview

on:
 workflow_dispatch: 

jobs:
 a_simple_job:
  name: my simple job name
  runs-on: ubuntu-latest
  steps:
   - name: name of my step
     id: stepId
     run: echo "This is the first setp from the first job"
   - name: another step with shell
     id:  shellStep
     shell: python
     run: print("this is using python shell\n")
